name: librecad
version: '2.2.1.2'
grade: stable
base: core22
confinement: strict
license: GPL-2.0
summary: "LibreCAD is a 2D open source CAD"
compression: lzo
description: |
  LibreCAD is a cross-platform 2D CAD program written in C++17. It can read DXF/DWG files
  and can write DXF/PDF/SVG files. It supports point/line/circle/ellipse/parabola/spline
  primitives. The user interface is highly customizable, and has dozens of translations.
  Code repository:
  https://www.github.com/LibreCAD/LibreCAD
environment:
  LD_LIBRARY_PATH: $SNAP/usr/local/lib/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/:$SNAP/usr/lib64/:$LD_LIBRARY_PATHapps:
  librecad:
    command: usr/bin/librecad
    plugs:
      - home
      - desktop
      - desktop-legacy
      - opengl
      - wayland
      - unity7
      - x11
      - removable-media
    desktop: usr/share/applications/org.librecad.librecad.desktop
    common-id: org.librecad.librecad.desktop
    environment:
      SNAP_DESKTOP_RUNTIME: $SNAP
      HOME: $SNAP_USER_DATAextensions:
  - kde-neon-6
  plugs:
  desktop:
    mount-host-font-cache: false
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themesparts:
  librecad:
    plugin: cmake
    source: https://github.com/LibreCAD/LibreCAD/archive/refs/tags/v2.2.1.2.tar.gz
    build-snaps:
      - kde-qt6-core22-sdk
    build-packages:
      - build-essential
      - libfreetype6-dev
      - libboost-dev
      - libgl1-mesa-dev
      - rsync
      - libcups2-dev
      - libv4lconvert0
    build-environment:
      - QT_SELECT: qt6
    override-build: |
      cmake $CRAFT_PART_SRC
      make -j$(nproc)
    stage:
      - -usr/share/pkgconfig
    override-install: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons
      mkdir -p $CRAFT_PART_INSTALL/usr/share/librecad/resources/qm
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications
      cp -a $CRAFT_PART_BUILD/librecad $CRAFT_PART_INSTALL/usr/bin/
      cp -a $CRAFT_PART_BUILD/.qm $CRAFT_PART_INSTALL/usr/share/librecad/resources/qm
      rsync -vaut $CRAFT_PART_SRC/librecad/support/ $CRAFT_PART_INSTALL/usr/share/librecad/resources/
      find $CRAFT_PART_SRC/CI -type f -name librecad.svg -exec cp -av '{}' $CRAFT_PART_INSTALL/usr/share/icons/ ;
      cp -a $CRAFT_PART_SRC/desktop/.desktop $CRAFT_PART_INSTALL/usr/share/applications/org.librecad.librecad.desktop
      sed -i'' -e 's:^\sIcon=.$:Icon=/usr/share/icons/librecad.svg:' $CRAFT_PART_INSTALL/usr/share/applications/org.librecad.librecad.desktop
      cp -a $CRAFT_PART_SRC/desktop/org.librecad..xml $CRAFT_PART_INSTALL/usr/share/applications/


