#!/usr/bin/env python3
"""gen_progress.py — render progress.json + PROGRESS.md from compute_progress().

Modes (subplans Part C.4.2):
  --write        regenerate docs/conformance/progress.json and PROGRESS.md
  --check        re-derive to a buffer and diff against committed files
"""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path

import conformance_stats as stats

REPO = Path(__file__).resolve().parents[2]
DOCS = REPO / "docs" / "conformance"
PROGRESS_JSON = DOCS / "progress.json"
PROGRESS_MD = DOCS / "PROGRESS.md"

STATE_ORDER = ["landed", "pushed", "committed", "validated", "in-progress",
               "planned", "deferred"]


def _render_progress_md(data: dict) -> str:
    agg = data["aggregate"]
    per = data["per_slice"]
    lines: list[str] = []
    lines.append("# PROGRESS.md — mechanically-derived per-slice state")
    lines.append("")
    lines.append("> **Generated by `scripts/conformance/gen_progress.py`.**")
    lines.append("> Do NOT hand-edit — every number is a live derivation from in-repo")
    lines.append("> artifacts and git. Run `gen_progress.py --write` to regenerate;")
    lines.append("> `gen_progress.py --check` verifies the file is not stale.")
    lines.append("")
    lines.append("## Aggregate scorecard")
    lines.append("")
    fields = [
        ("Branch", agg["branch"]),
        ("Tracked remote", agg["remote"]),
        ("Spec units", agg["spec_units"]),
        ("Spec data rows", agg["spec_data_rows"]),
        ("Code bodies", agg["code_bodies_total"]),
        ("Code total reads", agg["code_total_reads"]),
        ("Code total writes", agg["code_total_writes"]),
        ("Code delegation edges", agg["code_delegation_edges"]),
        ("Code DRW_UNUSED — real / param", f"{agg['code_drw_unused_real']} / {agg['code_drw_unused_param']}"),
        ("Ledger total rows", agg["ledger_total_rows"]),
        ("Ledger unaudited branch cells", agg["ledger_branch_cells_unaudited"]),
        ("Ledger named-untabled seeded", agg["ledger_named_untabled_seeded"]),
        ("Ledger unknowable seeded", agg["ledger_unknowable_seeded"]),
        ("Findings", agg["findings_count"]),
        ("Errata", agg["errata_count"]),
    ]
    for k, v in fields:
        lines.append(f"- **{k}**: {v}")
    lines.append("")

    # State-count summary
    lines.append("## Slice states")
    lines.append("")
    lines.append("| State | Count |")
    lines.append("|---|---|")
    for st in STATE_ORDER:
        n = data["state_counts"].get(st, 0)
        if n:
            lines.append(f"| {st} | {n} |")
    lines.append("")

    # Per-slice table, grouped by phase
    lines.append("## Per-slice detail")
    lines.append("")
    lines.append("| Phase | Slice ID | Kind | State | SHA | Reachable | On master | Title |")
    lines.append("|---|---|---|---|---|---|---|---|")
    per_sorted = sorted(per, key=lambda r: (r["phase_ord"], r["id"]))
    for r in per_sorted:
        sha = (r["commit_sha"] or "-")[:12]
        reach = "yes" if r["reachable_from_origin"] else "no"
        onm = "yes" if r["on_master"] else "no"
        lines.append(
            f"| {r['phase']} | `{r['id']}` | {r['kind']} | **{r['state']}** | "
            f"`{sha}` | {reach} | {onm} | {r['title']} |"
        )
    lines.append("")

    # Verdict-count summary from ledger
    vc = agg.get("ledger_verdict_counts") or {}
    if vc:
        lines.append("## Ledger verdict distribution")
        lines.append("")
        for verdict in sorted(vc.keys()):
            lines.append(f"- {verdict}: {vc[verdict]}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*This file is regenerated by `gen_progress.py --write`. The commit")
    lines.append("that landed this version of the generator wins over any hand-edit.*")
    return "\n".join(lines) + "\n"


def _render_progress_json(data: dict) -> str:
    return json.dumps(data, indent=2, sort_keys=True, ensure_ascii=True) + "\n"


def _write() -> int:
    data = stats.compute_progress()
    DOCS.mkdir(parents=True, exist_ok=True)
    PROGRESS_JSON.write_text(_render_progress_json(data), encoding="utf-8")
    PROGRESS_MD.write_text(_render_progress_md(data), encoding="utf-8")
    n = len(data["per_slice"])
    print(f"wrote {PROGRESS_JSON} + {PROGRESS_MD} — {n} slices")
    return 0


def _check() -> int:
    data = stats.compute_progress()
    fresh_json = _render_progress_json(data)
    fresh_md = _render_progress_md(data)
    ok = True
    if not PROGRESS_JSON.exists() or PROGRESS_JSON.read_text() != fresh_json:
        print("FAIL: progress.json is stale (or missing)", file=sys.stderr)
        ok = False
    if not PROGRESS_MD.exists() or PROGRESS_MD.read_text() != fresh_md:
        print("FAIL: PROGRESS.md is stale (or missing)", file=sys.stderr)
        ok = False
    if ok:
        print(f"PASS: progress files current ({len(data['per_slice'])} slices)")
        return 0
    print("run: python scripts/conformance/gen_progress.py --write", file=sys.stderr)
    return 1


def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    args = ap.parse_args()
    if args.write:
        return _write()
    if args.check:
        return _check()
    return 2


if __name__ == "__main__":
    sys.exit(main())
